version: '3.9'
services:
  hyperasnode:
    image: offchainlabs/nitro-node:v2.3.4-b4cc111
    ports:
      - "8547:8547"
      - "8548:8548"
      - "8642:9642"
    volumes:
      - "./config:/home/user/.arbitrum"
    command: 
      - --parent-chain.connection.url=https://sepolia-rollup.arbitrum.io/rpc
      - --chain.id=12489497903
      - --chain.name='Hyperas Chain Testnet'
      - --http.api=net,web3,eth
      - --http.corsdomain=*
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --chain.info-json="[{\"chain-id\":12489497903,\"parent-chain-id\":421614,\"parent-chain-is-arbitrum\":true,\"chain-name\":\"Hyperas Chain Testnet\",\"chain-config\":{\"homesteadBlock\":0,\"daoForkBlock\":null,\"daoForkSupport\":true,\"eip150Block\":0,\"eip150Hash\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"eip155Block\":0,\"eip158Block\":0,\"byzantiumBlock\":0,\"constantinopleBlock\":0,\"petersburgBlock\":0,\"istanbulBlock\":0,\"muirGlacierBlock\":0,\"berlinBlock\":0,\"londonBlock\":0,\"clique\":{\"period\":0,\"epoch\":0},\"arbitrum\":{\"EnableArbOS\":true,\"AllowDebugPrecompiles\":false,\"DataAvailabilityCommittee\":true,\"InitialArbOSVersion\":11,\"GenesisBlockNum\":0,\"MaxCodeSize\":24576,\"MaxInitCodeSize\":49152,\"InitialChainOwner\":\"0x6a77cc455bA677435C4a334bD5e6E9801722FbF9\"},\"chainId\":12489497903},\"rollup\":{\"bridge\":\"0xa3886969e8399bE96b34444EaAB5289C70614530\",\"inbox\":\"0xa22Ab2716c21DB473DDB0fd9d3435BF19eFFBC79\",\"sequencer-inbox\":\"0x12831e8AE02327BAb1c67dE359ce4d4923569407\",\"rollup\":\"0xAD2f28F06CBAb1831b6d529e45D1752b4FdCF199\",\"validator-utils\":\"0xB11EB62DD2B352886A4530A9106fE427844D515f\",\"validator-wallet-creator\":\"0xEb9885B6c0e117D339F47585cC06a2765AaE2E0b\",\"deployed-at\":58166021}}]"
      - --execution.forwarding-target=null
      - --node.data-availability.enable
      - --node.data-availability.rpc-aggregator.enable
      - --node.data-availability.rest-aggregator.enable
      - --node.data-availability.rest-aggregator.urls='[https://das-orbit.hyperaschain.com]'
      - --node.batch-poster.enable
      - --node.batch-poster.parent-chain-wallet.private-key=cfee27460029a09c927ecde286b93b127a1d154595c83bb8f63927d60ee38c16






  # das-server:
  #   image: offchainlabs/nitro-node:v2.3.3-6a1c1a7
  #   entrypoint: [ "/bin/bash", "/das-server.sh" ]
  #   volumes:
  #     - "./config:/home/user/.arbitrum"
  #     - "./das-server.sh:/das-server.sh"
  #     - "./das-data:/home/user/das-data"
  #   ports:
  #     - "9876:9876"
  #     - "9877:9877"
